package storage

import "errors"

var (
	ErrInvalidCredentials      = errors.New("invalid credentials")
	ErrUserExists              = errors.New("user already exists")
	ErrUserNotFound            = errors.New("user not found")
	ErrAppNotFound             = errors.New("app not found")
	ErrCreateUser              = errors.New("failed to create user")
	ErrCreateUserCommit        = errors.New("failed to create user")
	ErrLoginOrEmailExists      = errors.New("a user with the same login or email already exists, or the user already has the data")
	ErrVEmailExists            = errors.New("a user with the same login or email already exists")
	ErrOtherLoginOrEmail       = errors.New("unknown error")
	ErrOtherVemail             = errors.New("unknown error")
	ErrCreateMembInfo          = errors.New("failed to create information MembInfo")
	ErrCreateMembInfoCommit    = errors.New("failed to create information MembInfo")
	ErrGetMembInfo             = errors.New("failed to get information MembInfo")
	ErrCreateVmember           = errors.New("failed to create information Vmember")
	ErrCreateVmemberCommit     = errors.New("failed to create information Vmember")
	ErrCreatePassport          = errors.New("failed to create information Passport")
	ErrCreatePassportCommit    = errors.New("failed to create information Passport")
	ErrCheckUserRoleAndCompany = errors.New("failed check user role and company")
	ErrExistsName              = errors.New("the name already exists")
	ErrCreate                  = errors.New("failed to create information")
	ErrUnknown                 = errors.New("unknown error")
	ErrUpdateData              = errors.New("data update error")
	ErrNotFound                = errors.New("data not found")
	ErrCommit                  = errors.New("commit error")
	ErrExists                  = errors.New("the data already exists")
	ErrSave                    = errors.New("error update")
)
